// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using TransactionAppIOS.Helper;
using TransactionAppIOS.Model;
using TransactionAppIOS.ViewController;
using UIKit;

namespace TransactionAppIOS
{
	public partial class TansactionItemController : UITableViewController
	{
        List<TransactionItem> transactionItems = new List<TransactionItem>();
		public TansactionItemController (IntPtr handle) : base (handle)
		{
		}
        public override void LoadView()
        {
            base.LoadView();
        }
        public async  override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
            transactionItems = await ServiceHelper.Instance.GetTransactions();
            TableView.Source = new TransactionTableSource(transactionItems);
            TableView.RowHeight = UITableView.AutomaticDimension;
            TableView.EstimatedRowHeight = 40f;
            TableView.ReloadData();
        }
    }
}
