// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TransactionAppIOS
{
	public partial class TransactiopnDetailsViewController : UIViewController
	{
		public TransactiopnDetailsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
